import {
  Patient,
  Doctor,
  Department,
  Appointment,
  OPDQueueItem,
  Prescription,
  Admission,
  Bed,
  Ward,
  Medicine,
  LabTest,
  LabOrder,
  LabResult,
  Invoice,
  Payment,
  Staff,
  User,
  ActivityLog,
  NotificationItem,
  HospitalSettings,
  DashboardStatistics,
} from '../types';

export const INITIAL_HOSPITAL_SETTINGS: HospitalSettings = {
  name: 'St. Jude Apex Medical Center',
  address: '742 Healthcare Boulevard, Suite 500, Metro City',
  phone: '+1 (555) 349-8200',
  email: 'contact@stjudeapex.org',
  website: 'https://stjudeapex.health',
  registration_number: 'HC-REG-2024-8891-NY',
  currency: 'USD',
  currency_symbol: '$',
  timezone: 'America/New_York (EST)',
};

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept_01',
    name: 'Cardiology',
    code: 'CARD',
    description: 'Comprehensive cardiovascular care, diagnostic catheterization, and post-op care.',
    head_doctor: 'Dr. Arthur Campbell',
    head_doctor_id: 'doc_01',
    phone: '+1 (555) 349-8201',
    status: 'Active',
    total_doctors: 6,
    total_beds: 24,
  },
  {
    id: 'dept_02',
    name: 'Neurology',
    code: 'NEUR',
    description: 'Clinical neurophysiology, stroke interventions, and memory disorders unit.',
    head_doctor: 'Dr. Elena Rostova',
    head_doctor_id: 'doc_02',
    phone: '+1 (555) 349-8202',
    status: 'Active',
    total_doctors: 4,
    total_beds: 18,
  },
  {
    id: 'dept_03',
    name: 'Pediatrics',
    code: 'PED',
    description: 'Neonatal ICU, adolescent medicine, and developmental diagnostics.',
    head_doctor: 'Dr. Marcus Vance',
    head_doctor_id: 'doc_03',
    phone: '+1 (555) 349-8203',
    status: 'Active',
    total_doctors: 5,
    total_beds: 20,
  },
  {
    id: 'dept_04',
    name: 'Orthopedics',
    code: 'ORTH',
    description: 'Joint reconstruction, spine trauma surgery, and sports medicine rehab.',
    head_doctor: 'Dr. Sarah Jenkins',
    head_doctor_id: 'doc_04',
    phone: '+1 (555) 349-8204',
    status: 'Active',
    total_doctors: 7,
    total_beds: 28,
  },
  {
    id: 'dept_05',
    name: 'General Medicine',
    code: 'GENM',
    description: 'Internal medicine, adult preventative care, and chronic illness maintenance.',
    head_doctor: 'Dr. David Kim',
    head_doctor_id: 'doc_05',
    phone: '+1 (555) 349-8205',
    status: 'Active',
    total_doctors: 9,
    total_beds: 35,
  },
  {
    id: 'dept_06',
    name: 'Emergency & Trauma',
    code: 'EMRG',
    description: 'Level 1 Trauma center operational 24/7 with acute resuscitation bays.',
    head_doctor: 'Dr. Rachel Patel',
    head_doctor_id: 'doc_06',
    phone: '+1 (555) 349-8206',
    status: 'Active',
    total_doctors: 12,
    total_beds: 30,
  },
];

export const INITIAL_DOCTORS: Doctor[] = [
  {
    id: 'doc_01',
    doctor_id: 'DOC-1001',
    name: 'Dr. Arthur Campbell',
    email: 'a.campbell@hospital.org',
    phone: '+1 (555) 482-1011',
    gender: 'Male',
    specialization: 'Interventional Cardiology',
    department_id: 'dept_01',
    department_name: 'Cardiology',
    license_number: 'MD-NY-77281',
    experience: 16,
    status: 'Active',
    schedule: 'Mon, Wed, Fri (08:00 - 15:00)',
    available_days: ['Monday', 'Wednesday', 'Friday'],
  },
  {
    id: 'doc_02',
    doctor_id: 'DOC-1002',
    name: 'Dr. Elena Rostova',
    email: 'e.rostova@hospital.org',
    phone: '+1 (555) 482-1012',
    gender: 'Female',
    specialization: 'Neurocritical Care & Stroke',
    department_id: 'dept_02',
    department_name: 'Neurology',
    license_number: 'MD-NY-89104',
    experience: 12,
    status: 'Active',
    schedule: 'Tue, Thu, Sat (09:00 - 16:00)',
    available_days: ['Tuesday', 'Thursday', 'Saturday'],
  },
  {
    id: 'doc_03',
    doctor_id: 'DOC-1003',
    name: 'Dr. Marcus Vance',
    email: 'm.vance@hospital.org',
    phone: '+1 (555) 482-1013',
    gender: 'Male',
    specialization: 'Pediatric Pulmonology',
    department_id: 'dept_03',
    department_name: 'Pediatrics',
    license_number: 'MD-NY-66120',
    experience: 9,
    status: 'Active',
    schedule: 'Mon, Tue, Thu (08:30 - 14:30)',
    available_days: ['Monday', 'Tuesday', 'Thursday'],
  },
  {
    id: 'doc_04',
    doctor_id: 'DOC-1004',
    name: 'Dr. Sarah Jenkins',
    email: 's.jenkins@hospital.org',
    phone: '+1 (555) 482-1014',
    gender: 'Female',
    specialization: 'Spine & Trauma Surgery',
    department_id: 'dept_04',
    department_name: 'Orthopedics',
    license_number: 'MD-NY-90234',
    experience: 14,
    status: 'Active',
    schedule: 'Wed, Fri (07:30 - 16:00)',
    available_days: ['Wednesday', 'Friday'],
  },
  {
    id: 'doc_05',
    doctor_id: 'DOC-1005',
    name: 'Dr. David Kim',
    email: 'd.kim@hospital.org',
    phone: '+1 (555) 482-1015',
    gender: 'Male',
    specialization: 'Internal Medicine',
    department_id: 'dept_05',
    department_name: 'General Medicine',
    license_number: 'MD-NY-55119',
    experience: 11,
    status: 'Active',
    schedule: 'Mon - Fri (09:00 - 17:00)',
    available_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
  },
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'pat_01',
    patient_id: 'PAT-0091',
    first_name: 'Jonathan',
    last_name: 'Hayes',
    gender: 'Male',
    date_of_birth: '1979-04-14',
    phone: '+1 (555) 831-2940',
    email: 'j.hayes@example.com',
    address: '428 Elm Ridge Road, Apt 4B, Metro City',
    blood_group: 'O+',
    marital_status: 'Married',
    emergency_contact: 'Clara Hayes (Wife)',
    emergency_phone: '+1 (555) 831-2945',
    allergies: 'Penicillin, Sulfa drugs',
    medical_notes: 'History of hypertension stage 1, coronary artery spasm under monitoring.',
    status: 'Active',
    created_at: '2024-02-15T10:30:00Z',
  },
  {
    id: 'pat_02',
    patient_id: 'PAT-0092',
    first_name: 'Miriam',
    last_name: 'Al-Mansoor',
    gender: 'Female',
    date_of_birth: '1992-11-03',
    phone: '+1 (555) 412-9831',
    email: 'm.almansoor@example.com',
    address: '109 Riverside Terrace, Metro City',
    blood_group: 'B+',
    marital_status: 'Single',
    emergency_contact: 'Tariq Al-Mansoor (Brother)',
    emergency_phone: '+1 (555) 412-9838',
    allergies: 'Aspirin, Shellfish',
    medical_notes: 'Chronic migraines with aura; occasional tension cephalea.',
    status: 'Active',
    created_at: '2024-03-01T14:15:00Z',
  },
  {
    id: 'pat_03',
    patient_id: 'PAT-0093',
    first_name: 'Samuel',
    last_name: 'O’Connor',
    gender: 'Male',
    date_of_birth: '1965-08-22',
    phone: '+1 (555) 902-1847',
    email: 's.oconnor@example.com',
    address: '88 Harborview Walk, Metro City',
    blood_group: 'A-',
    marital_status: 'Married',
    emergency_contact: 'Eileen O’Connor (Spouse)',
    emergency_phone: '+1 (555) 902-1850',
    allergies: 'None recorded',
    medical_notes: 'Type 2 Diabetes Mellitus managed with Metformin. Annual ophthalmology clear.',
    status: 'Active',
    created_at: '2024-03-10T09:00:00Z',
  },
  {
    id: 'pat_04',
    patient_id: 'PAT-0094',
    first_name: 'Evelyn',
    last_name: 'Chen',
    gender: 'Female',
    date_of_birth: '2016-06-19',
    phone: '+1 (555) 723-5591',
    email: 'chen.family@example.com',
    address: '15 Maple Grove Lane, Metro City',
    blood_group: 'AB+',
    marital_status: 'Single',
    emergency_contact: 'Wei Chen (Father)',
    emergency_phone: '+1 (555) 723-5592',
    allergies: 'Peanuts, Tree nuts',
    medical_notes: 'Pediatric asthma mild intermittent; albuterol inhaler PRN.',
    status: 'Active',
    created_at: '2024-04-05T11:20:00Z',
  },
  {
    id: 'pat_05',
    patient_id: 'PAT-0095',
    first_name: 'Robert',
    last_name: 'Sterling',
    gender: 'Male',
    date_of_birth: '1954-01-29',
    phone: '+1 (555) 604-3318',
    email: 'r.sterling@example.com',
    address: '302 Birchwood Court, Metro City',
    blood_group: 'O-',
    marital_status: 'Widowed',
    emergency_contact: 'Mark Sterling (Son)',
    emergency_phone: '+1 (555) 604-3320',
    allergies: 'Iodinated contrast media',
    medical_notes: 'Post total hip arthroplasty (right, 2023). Mild osteoarthritis left knee.',
    status: 'Active',
    created_at: '2024-04-12T16:45:00Z',
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt_01',
    appointment_number: 'APT-2026-081',
    patient_id: 'pat_01',
    patient_name: 'Jonathan Hayes',
    patient_phone: '+1 (555) 831-2940',
    doctor_id: 'doc_01',
    doctor_name: 'Dr. Arthur Campbell',
    department_id: 'dept_01',
    department_name: 'Cardiology',
    appointment_date: new Date().toISOString().split('T')[0],
    appointment_time: '09:30',
    type: 'Follow-up',
    reason: 'Review 24-hr Holter monitor findings and titration of antihypertensive.',
    notes: 'Patient reported minor dizziness on rising last Thursday.',
    status: 'In Consultation' as any,
  },
  {
    id: 'apt_02',
    appointment_number: 'APT-2026-082',
    patient_id: 'pat_02',
    patient_name: 'Miriam Al-Mansoor',
    patient_phone: '+1 (555) 412-9831',
    doctor_id: 'doc_02',
    doctor_name: 'Dr. Elena Rostova',
    department_id: 'dept_02',
    department_name: 'Neurology',
    appointment_date: new Date().toISOString().split('T')[0],
    appointment_time: '10:15',
    type: 'Specialist Consultation',
    reason: 'Evaluation of persistent visual aura episodes.',
    notes: 'Requesting review of brain MRI scans completed last week.',
    status: 'Waiting',
  },
  {
    id: 'apt_03',
    appointment_number: 'APT-2026-083',
    patient_id: 'pat_03',
    patient_name: 'Samuel O’Connor',
    patient_phone: '+1 (555) 902-1847',
    doctor_id: 'doc_05',
    doctor_name: 'Dr. David Kim',
    department_id: 'dept_05',
    department_name: 'General Medicine',
    appointment_date: new Date().toISOString().split('T')[0],
    appointment_time: '11:00',
    type: 'Routine',
    reason: 'Quarterly HbA1c review and diabetic foot check.',
    notes: 'Fasting labs drawn 2 days prior at hospital laboratory.',
    status: 'Confirmed',
  },
  {
    id: 'apt_04',
    appointment_number: 'APT-2026-084',
    patient_id: 'pat_04',
    patient_name: 'Evelyn Chen',
    patient_phone: '+1 (555) 723-5591',
    doctor_id: 'doc_03',
    doctor_name: 'Dr. Marcus Vance',
    department_id: 'dept_03',
    department_name: 'Pediatrics',
    appointment_date: new Date().toISOString().split('T')[0],
    appointment_time: '14:00',
    type: 'Follow-up',
    reason: 'Check peak flow meter readings and spring pollen trigger adjustment.',
    status: 'Scheduled',
  },
  {
    id: 'apt_05',
    appointment_number: 'APT-2026-085',
    patient_id: 'pat_05',
    patient_name: 'Robert Sterling',
    patient_phone: '+1 (555) 604-3318',
    doctor_id: 'doc_04',
    doctor_name: 'Dr. Sarah Jenkins',
    department_id: 'dept_04',
    department_name: 'Orthopedics',
    appointment_date: new Date().toISOString().split('T')[0],
    appointment_time: '08:45',
    type: 'Routine',
    reason: '6-month postoperative range of motion inspection.',
    status: 'Completed',
  },
];

export const INITIAL_OPD_QUEUE: OPDQueueItem[] = [
  {
    id: 'opd_01',
    queue_number: 101,
    appointment_id: 'apt_01',
    patient_id: 'pat_01',
    patient_name: 'Jonathan Hayes',
    doctor_id: 'doc_01',
    doctor_name: 'Dr. Arthur Campbell',
    department_name: 'Cardiology',
    appointment_time: '09:30',
    priority: 'Normal',
    status: 'In Consultation',
    vitals: {
      blood_pressure: '138/86 mmHg',
      heart_rate: 74,
      temperature: 98.4,
      respiratory_rate: 16,
      oxygen_saturation: 98,
      weight: 84.5,
      height: 178,
    },
    symptoms: 'Mild post-exercise exertional fatigue, episodic chest tightness resolving within 2 minutes.',
  },
  {
    id: 'opd_02',
    queue_number: 102,
    appointment_id: 'apt_02',
    patient_id: 'pat_02',
    patient_name: 'Miriam Al-Mansoor',
    doctor_id: 'doc_02',
    doctor_name: 'Dr. Elena Rostova',
    department_name: 'Neurology',
    appointment_time: '10:15',
    priority: 'Urgent',
    status: 'Waiting',
    vitals: {
      blood_pressure: '118/74 mmHg',
      heart_rate: 80,
      temperature: 98.6,
      respiratory_rate: 14,
      oxygen_saturation: 99,
      weight: 61.0,
      height: 165,
    },
    symptoms: 'Scintillating scotoma left visual field, photophobia, throbbing hemicranial pain.',
  },
  {
    id: 'opd_03',
    queue_number: 103,
    appointment_id: 'apt_03',
    patient_id: 'pat_03',
    patient_name: 'Samuel O’Connor',
    doctor_id: 'doc_05',
    doctor_name: 'Dr. David Kim',
    department_name: 'General Medicine',
    appointment_time: '11:00',
    priority: 'Normal',
    status: 'Waiting',
    vitals: {
      blood_pressure: '126/80 mmHg',
      heart_rate: 68,
      temperature: 98.2,
      respiratory_rate: 15,
      oxygen_saturation: 97,
      weight: 89.2,
      height: 175,
    },
    symptoms: 'Routine diabetic follow-up; no acute dysesthesia.',
  },
];

export const INITIAL_PRESCRIPTIONS: Prescription[] = [
  {
    id: 'rx_01',
    prescription_number: 'RX-8821',
    patient_id: 'pat_01',
    patient_name: 'Jonathan Hayes',
    patient_age: 47,
    patient_gender: 'Male',
    doctor_id: 'doc_01',
    doctor_name: 'Dr. Arthur Campbell',
    doctor_specialization: 'Interventional Cardiology',
    doctor_license: 'MD-NY-77281',
    date: new Date().toISOString().split('T')[0],
    diagnosis: 'Essential Hypertension Stage 1 / Angina pectoris suspected',
    notes: 'Take with morning food. Maintain low sodium diet. Avoid NSAIDs.',
    medicines: [
      {
        id: 'rx_m_01',
        medicine_name: 'Amlodipine Besylate',
        dosage: '5mg',
        frequency: 'Once Daily (Morning)',
        duration: '30 days',
        route: 'Oral',
        instructions: 'Take 1 tablet every morning with water.',
      },
      {
        id: 'rx_m_02',
        medicine_name: 'Atorvastatin Calcium',
        dosage: '20mg',
        frequency: 'Once Daily (Bedtime)',
        duration: '30 days',
        route: 'Oral',
        instructions: 'Take 1 tablet at bedtime.',
      },
      {
        id: 'rx_m_03',
        medicine_name: 'Nitroglycerin Sublingual',
        dosage: '0.4mg',
        frequency: 'PRN (As Needed)',
        duration: '30 days',
        route: 'Sublingual',
        instructions: 'Dissolve 1 tablet under tongue for acute chest tightness. Seek ER if unresolved after 5 mins.',
      },
    ],
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_WARDS: Ward[] = [
  {
    id: 'w_01',
    name: 'Cardiovascular Care Ward',
    code: 'W-CARD-A',
    type: 'Specialized',
    floor: 'Floor 3, East Wing',
    capacity: 12,
    occupied: 8,
    available: 4,
  },
  {
    id: 'w_02',
    name: 'Intensive Care Unit (ICU)',
    code: 'W-ICU-1',
    type: 'Critical Care',
    floor: 'Floor 2, Critical Care Tower',
    capacity: 10,
    occupied: 7,
    available: 3,
  },
  {
    id: 'w_03',
    name: 'Orthopedic Recovery Unit',
    code: 'W-ORTH-B',
    type: 'Surgical/Post-Op',
    floor: 'Floor 4, West Wing',
    capacity: 14,
    occupied: 9,
    available: 5,
  },
  {
    id: 'w_04',
    name: 'Pediatric Care Ward',
    code: 'W-PED-C',
    type: 'Pediatric',
    floor: 'Floor 5, North Pavilion',
    capacity: 12,
    occupied: 5,
    available: 7,
  },
];

export const INITIAL_BEDS: Bed[] = [
  { id: 'b_01', bed_number: 'B-301-A', room_number: '301', ward_id: 'w_01', ward_name: 'Cardiovascular Care Ward', type: 'General', status: 'Occupied', current_patient_id: 'pat_01', current_patient_name: 'Jonathan Hayes', daily_rate: 320 },
  { id: 'b_02', bed_number: 'B-301-B', room_number: '301', ward_id: 'w_01', ward_name: 'Cardiovascular Care Ward', type: 'General', status: 'Available', daily_rate: 320 },
  { id: 'b_03', bed_number: 'B-302-A', room_number: '302', ward_id: 'w_01', ward_name: 'Cardiovascular Care Ward', type: 'Semi-Private', status: 'Occupied', current_patient_name: 'Harold Green', daily_rate: 480 },
  { id: 'b_04', bed_number: 'B-302-B', room_number: '302', ward_id: 'w_01', ward_name: 'Cardiovascular Care Ward', type: 'Semi-Private', status: 'Reserved', daily_rate: 480 },
  { id: 'b_05', bed_number: 'ICU-201', room_number: 'ICU-1', ward_id: 'w_02', ward_name: 'Intensive Care Unit (ICU)', type: 'ICU', status: 'Occupied', current_patient_name: 'Angela Ross', daily_rate: 1450 },
  { id: 'b_06', bed_number: 'ICU-202', room_number: 'ICU-2', ward_id: 'w_02', ward_name: 'Intensive Care Unit (ICU)', type: 'ICU', status: 'Available', daily_rate: 1450 },
  { id: 'b_07', bed_number: 'ICU-203', room_number: 'ICU-3', ward_id: 'w_02', ward_name: 'Intensive Care Unit (ICU)', type: 'ICU', status: 'Maintenance', daily_rate: 1450 },
  { id: 'b_08', bed_number: 'B-401-A', room_number: '401', ward_id: 'w_03', ward_name: 'Orthopedic Recovery Unit', type: 'General', status: 'Occupied', current_patient_id: 'pat_05', current_patient_name: 'Robert Sterling', daily_rate: 350 },
  { id: 'b_09', bed_number: 'B-401-B', room_number: '401', ward_id: 'w_03', ward_name: 'Orthopedic Recovery Unit', type: 'General', status: 'Available', daily_rate: 350 },
  { id: 'b_10', bed_number: 'B-402-A', room_number: '402', ward_id: 'w_03', ward_name: 'Orthopedic Recovery Unit', type: 'Semi-Private', status: 'Available', daily_rate: 510 },
  { id: 'b_11', bed_number: 'PED-501', room_number: '501', ward_id: 'w_04', ward_name: 'Pediatric Care Ward', type: 'Pediatric', status: 'Available', daily_rate: 300 },
  { id: 'b_12', bed_number: 'PED-502', room_number: '502', ward_id: 'w_04', ward_name: 'Pediatric Care Ward', type: 'Pediatric', status: 'Available', daily_rate: 300 },
];

export const INITIAL_ADMISSIONS: Admission[] = [
  {
    id: 'adm_01',
    admission_number: 'ADM-2026-044',
    patient_id: 'pat_01',
    patient_name: 'Jonathan Hayes',
    doctor_id: 'doc_01',
    doctor_name: 'Dr. Arthur Campbell',
    ward: 'Cardiovascular Care Ward',
    room: '301',
    bed: 'B-301-A',
    admission_date: new Date(Date.now() - 36 * 3600 * 1000).toISOString().split('T')[0],
    diagnosis: 'Acute Coronary Syndrome r/o NSTEMI',
    notes: 'Continuous cardiac telemetry, daily cardiac biomarkers panel.',
    status: 'Admitted',
  },
  {
    id: 'adm_02',
    admission_number: 'ADM-2026-041',
    patient_id: 'pat_05',
    patient_name: 'Robert Sterling',
    doctor_id: 'doc_04',
    doctor_name: 'Dr. Sarah Jenkins',
    ward: 'Orthopedic Recovery Unit',
    room: '401',
    bed: 'B-401-A',
    admission_date: new Date(Date.now() - 72 * 3600 * 1000).toISOString().split('T')[0],
    diagnosis: 'Left Hip Revision Arthroplasty',
    notes: 'Physical therapy twice daily; wound drainage minimal and clean.',
    status: 'Admitted',
  },
];

export const INITIAL_MEDICINES: Medicine[] = [
  {
    id: 'med_01',
    name: 'Amoxicillin / Clavulanate 875/125mg',
    generic_name: 'Augmentin',
    category: 'Antibiotics',
    manufacturer: 'GlaxoSmithKline',
    batch_number: 'BAT-2025-9921',
    expiry_date: '2027-08-30',
    unit: 'Tablet',
    purchase_price: 0.85,
    selling_price: 2.10,
    quantity: 450,
    minimum_stock: 100,
    status: 'Available',
  },
  {
    id: 'med_02',
    name: 'Amlodipine Besylate 5mg',
    generic_name: 'Norvasc',
    category: 'Cardiovascular',
    manufacturer: 'Pfizer Inc.',
    batch_number: 'BAT-2025-4102',
    expiry_date: '2027-11-15',
    unit: 'Tablet',
    purchase_price: 0.20,
    selling_price: 0.75,
    quantity: 680,
    minimum_stock: 150,
    status: 'Available',
  },
  {
    id: 'med_03',
    name: 'Atorvastatin 20mg',
    generic_name: 'Lipitor',
    category: 'Cardiovascular',
    manufacturer: 'Viatris',
    batch_number: 'BAT-2025-1193',
    expiry_date: '2028-01-20',
    unit: 'Tablet',
    purchase_price: 0.35,
    selling_price: 1.25,
    quantity: 28,
    minimum_stock: 50,
    status: 'Low Stock',
  },
  {
    id: 'med_04',
    name: 'Metformin Hydrochloride 500mg',
    generic_name: 'Glucophage',
    category: 'Antidiabetic',
    manufacturer: 'Merck Healthcare',
    batch_number: 'BAT-2025-3382',
    expiry_date: '2027-04-10',
    unit: 'Tablet',
    purchase_price: 0.15,
    selling_price: 0.50,
    quantity: 820,
    minimum_stock: 200,
    status: 'Available',
  },
  {
    id: 'med_05',
    name: 'Salbutamol HFA Inhaler 100mcg',
    generic_name: 'Ventolin',
    category: 'Respiratory',
    manufacturer: 'GlaxoSmithKline',
    batch_number: 'BAT-2024-8812',
    expiry_date: '2026-10-15',
    unit: 'Inhaler',
    purchase_price: 8.50,
    selling_price: 19.00,
    quantity: 14,
    minimum_stock: 25,
    status: 'Expiring Soon',
  },
  {
    id: 'med_06',
    name: 'Ceftriaxone Sodium 1g Vial',
    generic_name: 'Rocephin',
    category: 'Injectable Antibiotic',
    manufacturer: 'Roche Pharma',
    batch_number: 'BAT-2024-0012',
    expiry_date: '2026-03-01',
    unit: 'Vial',
    purchase_price: 4.20,
    selling_price: 12.50,
    quantity: 0,
    minimum_stock: 30,
    status: 'Expired',
  },
];

export const INITIAL_LAB_TESTS: LabTest[] = [
  {
    id: 't_01',
    code: 'CBC-01',
    name: 'Complete Blood Count (CBC) with Differential',
    category: 'Hematology',
    description: 'Quantitative count of RBC, WBC, Hemoglobin, Hematocrit, and Platelets.',
    price: 45.00,
    normal_range: 'WBC: 4.5-11.0 K/uL, RBC: 4.3-5.9 M/uL, Hb: 13.5-17.5 g/dL',
    unit: 'Various',
    status: 'Active',
  },
  {
    id: 't_02',
    code: 'CMP-02',
    name: 'Comprehensive Metabolic Panel (CMP)',
    category: 'Biochemistry',
    description: 'Assesses kidney function, liver enzymes, electrolyte and fluid balance.',
    price: 65.00,
    normal_range: 'Glucose: 70-99 mg/dL, BUN: 7-20 mg/dL, Creatinine: 0.7-1.3 mg/dL',
    unit: 'mg/dL',
    status: 'Active',
  },
  {
    id: 't_03',
    code: 'LIP-03',
    name: 'Lipid Profile Extended',
    category: 'Biochemistry',
    description: 'Total Cholesterol, HDL, LDL, Triglycerides, and VLDL assessment.',
    price: 55.00,
    normal_range: 'Total Chol < 200 mg/dL, LDL < 100 mg/dL, HDL > 40 mg/dL',
    unit: 'mg/dL',
    status: 'Active',
  },
  {
    id: 't_04',
    code: 'TROP-04',
    name: 'High-Sensitivity Troponin I (hs-cTnI)',
    category: 'Cardiology Diagnostics',
    description: 'Rapid quantitative biomarker for myocardial injury or acute infarction.',
    price: 90.00,
    normal_range: '< 14 ng/L (Normal Baseline)',
    unit: 'ng/L',
    status: 'Active',
  },
  {
    id: 't_05',
    code: 'HBA1C-05',
    name: 'Glycated Hemoglobin (HbA1c)',
    category: 'Endocrinology',
    description: 'Provides estimated average blood glucose level over preceding 90 days.',
    price: 50.00,
    normal_range: '< 5.7% Normal, 5.7-6.4% Prediabetes, >=6.5% Diabetes',
    unit: '%',
    status: 'Active',
  },
];

export const INITIAL_LAB_ORDERS: LabOrder[] = [
  {
    id: 'lo_01',
    order_number: 'LAB-2026-1102',
    patient_id: 'pat_01',
    patient_name: 'Jonathan Hayes',
    doctor_id: 'doc_01',
    doctor_name: 'Dr. Arthur Campbell',
    test_ids: ['t_04', 't_02'],
    test_names: ['High-Sensitivity Troponin I (hs-cTnI)', 'Comprehensive Metabolic Panel (CMP)'],
    priority: 'Urgent',
    sample_type: 'Venous Blood (Heparin / SST)',
    order_date: new Date().toISOString(),
    status: 'In Progress',
  },
  {
    id: 'lo_02',
    order_number: 'LAB-2026-1101',
    patient_id: 'pat_03',
    patient_name: 'Samuel O’Connor',
    doctor_id: 'doc_05',
    doctor_name: 'Dr. David Kim',
    test_ids: ['t_05', 't_03'],
    test_names: ['Glycated Hemoglobin (HbA1c)', 'Lipid Profile Extended'],
    priority: 'Normal',
    sample_type: 'Whole Blood (EDTA tube)',
    order_date: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    status: 'Completed',
  },
];

export const INITIAL_LAB_RESULTS: LabResult[] = [
  {
    id: 'lr_01',
    order_id: 'lo_02',
    order_number: 'LAB-2026-1101',
    test_id: 't_05',
    test_name: 'Glycated Hemoglobin (HbA1c)',
    patient_id: 'pat_03',
    patient_name: 'Samuel O’Connor',
    result: '6.8%',
    reference_range: '< 5.7% (Optimal)',
    unit: '%',
    status: 'Abnormal',
    remarks: 'Moderate glycemic elevation; continue current oral hypoglycemic regimen.',
    technician: 'Clara Oswald, MLS(ASCP)',
    date: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
  },
  {
    id: 'lr_02',
    order_id: 'lo_02',
    order_number: 'LAB-2026-1101',
    test_id: 't_03',
    test_name: 'Lipid Profile Extended (LDL)',
    patient_id: 'pat_03',
    patient_name: 'Samuel O’Connor',
    result: '112 mg/dL',
    reference_range: '< 100 mg/dL',
    unit: 'mg/dL',
    status: 'Abnormal',
    remarks: 'Borderline elevated LDL cholesterol.',
    technician: 'Clara Oswald, MLS(ASCP)',
    date: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv_01',
    invoice_number: 'INV-2026-0091',
    patient_id: 'pat_01',
    patient_name: 'Jonathan Hayes',
    patient_phone: '+1 (555) 831-2940',
    date: new Date().toISOString().split('T')[0],
    due_date: new Date(Date.now() + 14 * 86400 * 1000).toISOString().split('T')[0],
    items: [
      { id: 'itm_1', description: 'Emergency Consultation & Triage', category: 'Consultation', quantity: 1, unit_price: 250, total: 250 },
      { id: 'itm_2', description: 'High-Sensitivity Troponin I (Serial 2x)', category: 'Laboratory', quantity: 2, unit_price: 90, total: 180 },
      { id: 'itm_3', description: 'ECG 12-Lead Diagnostic Interpretation', category: 'Procedure', quantity: 1, unit_price: 120, total: 120 },
      { id: 'itm_4', description: 'Cardiovascular Care Ward Bed (2 Days)', category: 'Room/Bed', quantity: 2, unit_price: 320, total: 640 },
    ],
    subtotal: 1190,
    discount: 50,
    tax: 0,
    total: 1140,
    paid: 600,
    balance: 540,
    status: 'Partial',
    payment_method: 'Insurance + Credit Card',
    created_at: new Date().toISOString(),
  },
  {
    id: 'inv_02',
    invoice_number: 'INV-2026-0092',
    patient_id: 'pat_03',
    patient_name: 'Samuel O’Connor',
    patient_phone: '+1 (555) 902-1847',
    date: new Date(Date.now() - 48 * 3600 * 1000).toISOString().split('T')[0],
    due_date: new Date(Date.now() + 10 * 86400 * 1000).toISOString().split('T')[0],
    items: [
      { id: 'itm_5', description: 'General Medicine Consultation', category: 'Consultation', quantity: 1, unit_price: 150, total: 150 },
      { id: 'itm_6', description: 'HbA1c & Lipid Panel', category: 'Laboratory', quantity: 1, unit_price: 105, total: 105 },
    ],
    subtotal: 255,
    discount: 0,
    tax: 0,
    total: 255,
    paid: 255,
    balance: 0,
    status: 'Paid',
    payment_method: 'Debit Card',
    created_at: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
  },
  {
    id: 'inv_03',
    invoice_number: 'INV-2026-0093',
    patient_id: 'pat_05',
    patient_name: 'Robert Sterling',
    patient_phone: '+1 (555) 604-3318',
    date: new Date(Date.now() - 72 * 3600 * 1000).toISOString().split('T')[0],
    due_date: new Date(Date.now() + 20 * 86400 * 1000).toISOString().split('T')[0],
    items: [
      { id: 'itm_7', description: 'Orthopedic Arthroplasty Surgical Suite Fee', category: 'Procedure', quantity: 1, unit_price: 4800, total: 4800 },
      { id: 'itm_8', description: 'Orthopedic Recovery Bed (3 Days)', category: 'Room/Bed', quantity: 3, unit_price: 350, total: 1050 },
      { id: 'itm_9', description: 'Post-Op Physical Rehabilitation Session', category: 'Procedure', quantity: 2, unit_price: 180, total: 360 },
    ],
    subtotal: 6210,
    discount: 210,
    tax: 0,
    total: 6000,
    paid: 0,
    balance: 6000,
    status: 'Pending',
    created_at: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay_01',
    receipt_number: 'REC-2026-091',
    invoice_id: 'inv_01',
    invoice_number: 'INV-2026-0091',
    patient_name: 'Jonathan Hayes',
    amount: 600.00,
    payment_date: new Date().toISOString().split('T')[0],
    payment_method: 'Credit Card',
    notes: 'Initial admission deposit authorized by patient.',
  },
  {
    id: 'pay_02',
    receipt_number: 'REC-2026-090',
    invoice_id: 'inv_02',
    invoice_number: 'INV-2026-0092',
    patient_name: 'Samuel O’Connor',
    amount: 255.00,
    payment_date: new Date(Date.now() - 48 * 3600 * 1000).toISOString().split('T')[0],
    payment_method: 'Debit Card',
    notes: 'Full payment for OPD consultation and labs.',
  },
];

export const INITIAL_STAFF: Staff[] = [
  { id: 'st_01', staff_id: 'STF-01', name: 'Dr. Arthur Campbell', email: 'a.campbell@hospital.org', phone: '+1 (555) 482-1011', role: 'Doctor', department: 'Cardiology', status: 'Active', joined_date: '2018-03-12' },
  { id: 'st_02', staff_id: 'STF-02', name: 'Nurse Beatrice Morales', email: 'b.morales@hospital.org', phone: '+1 (555) 482-1020', role: 'Nurse', department: 'Emergency & Trauma', status: 'Active', joined_date: '2020-07-15' },
  { id: 'st_03', staff_id: 'STF-03', name: 'Fiona Gallagher', email: 'f.gallagher@hospital.org', phone: '+1 (555) 482-1035', role: 'Pharmacist', department: 'Pharmacy', status: 'Active', joined_date: '2021-01-20' },
  { id: 'st_04', staff_id: 'STF-04', name: 'Clara Oswald', email: 'c.oswald@hospital.org', phone: '+1 (555) 482-1044', role: 'Laboratory Staff', department: 'Laboratory', status: 'Active', joined_date: '2022-04-18' },
  { id: 'st_05', staff_id: 'STF-05', name: 'Julian Drake', email: 'j.drake@hospital.org', phone: '+1 (555) 482-1052', role: 'Accountant', department: 'Finance & Billing', status: 'Active', joined_date: '2019-10-01' },
  { id: 'st_06', staff_id: 'STF-06', name: 'Hannah Wright', email: 'h.wright@hospital.org', phone: '+1 (555) 482-1061', role: 'Receptionist', department: 'Outpatient Desk', status: 'Active', joined_date: '2023-05-11' },
];

export const INITIAL_USERS: User[] = [
  { id: 'usr_01', name: 'Dr. Arthur Campbell', email: 'admin@hospital.org', role: 'Super Admin', status: 'Active', last_login: new Date().toISOString(), created_at: '2023-01-01' },
  { id: 'usr_02', name: 'Dr. Elena Rostova', email: 'e.rostova@hospital.org', role: 'Doctor', status: 'Active', last_login: '2026-09-20T11:00:00Z', created_at: '2023-03-15' },
  { id: 'usr_03', name: 'Nurse Beatrice Morales', email: 'b.morales@hospital.org', role: 'Nurse', status: 'Active', last_login: '2026-09-21T07:30:00Z', created_at: '2023-06-10' },
  { id: 'usr_04', name: 'Fiona Gallagher', email: 'pharmacy@hospital.org', role: 'Pharmacist', status: 'Active', last_login: '2026-09-21T08:15:00Z', created_at: '2023-07-20' },
  { id: 'usr_05', name: 'Julian Drake', email: 'billing@hospital.org', role: 'Accountant', status: 'Active', last_login: '2026-09-21T14:40:00Z', created_at: '2023-08-01' },
  { id: 'usr_06', name: 'Hannah Wright', email: 'reception@hospital.org', role: 'Receptionist', status: 'Active', last_login: '2026-09-22T08:00:00Z', created_at: '2023-09-12' },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  { id: 'act_01', user_name: 'Dr. Arthur Campbell', user_role: 'Super Admin', action: 'CREATE_CONSULTATION', module: 'OPD', description: 'Recorded consultation and vitals for patient PAT-0091', ip_address: '192.168.1.42', created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString() },
  { id: 'act_02', user_name: 'Fiona Gallagher', user_role: 'Pharmacist', action: 'DISPENSE_MEDICINE', module: 'Pharmacy', description: 'Dispensed 30 tablets of Amlodipine 5mg on Rx-8821', ip_address: '192.168.1.18', created_at: new Date(Date.now() - 42 * 60 * 1000).toISOString() },
  { id: 'act_03', user_name: 'Hannah Wright', user_role: 'Receptionist', action: 'BOOK_APPOINTMENT', module: 'Appointments', description: 'Scheduled cardiology checkup for Miriam Al-Mansoor', ip_address: '192.168.1.10', created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString() },
  { id: 'act_04', user_name: 'Julian Drake', user_role: 'Accountant', action: 'RECORD_PAYMENT', module: 'Billing', description: 'Logged $600 deposit against invoice INV-2026-0091', ip_address: '192.168.1.25', created_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString() },
  { id: 'act_05', user_name: 'Dr. Sarah Jenkins', user_role: 'Doctor', action: 'ADMIT_PATIENT', module: 'IPD', description: 'Admitted Robert Sterling to Orthopedic Ward Room 401 Bed B-401-A', ip_address: '192.168.1.66', created_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString() },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  { id: 'notif_01', type: 'appointment', title: 'Upcoming Cardiology Consultation', message: 'Jonathan Hayes is queued at Room 302 for 09:30 checkup.', read: false, created_at: '10 mins ago', link: '/opd/queue' },
  { id: 'notif_02', type: 'pharmacy', title: 'Low Stock Warning', message: 'Atorvastatin 20mg inventory has dropped below the threshold of 50 units (28 remaining).', read: false, created_at: '45 mins ago', link: '/pharmacy/stock' },
  { id: 'notif_03', type: 'lab', title: 'Urgent Lab Order Pending', message: 'High-Sensitivity Troponin I ordered for patient PAT-0091 requires processing.', read: false, created_at: '1 hour ago', link: '/laboratory/orders' },
  { id: 'notif_04', type: 'billing', title: 'High-Value Invoice Generated', message: 'Invoice INV-2026-0093 for $6,000.00 created for patient Robert Sterling.', read: true, created_at: '3 hours ago', link: '/billing/invoices' },
  { id: 'notif_05', type: 'ipd', title: 'Bed Occupancy Update', message: 'Cardiovascular Care Ward reached 66.7% occupancy with 4 available beds remaining.', read: true, created_at: 'Yesterday', link: '/ipd/beds' },
];

export const INITIAL_DASHBOARD_STATS: DashboardStatistics = {
  total_patients: 12450,
  patients_trend: 12.5,
  total_doctors: 86,
  today_appointments: 128,
  available_beds: 42,
  total_beds: 120,
  today_admissions: 14,
  pending_bills: 28,
  monthly_revenue: 458200,
  revenue_trend: 8.4,
  pending_lab_tests: 19,
  weekly_patients: [
    { day: 'Mon', admitted: 18, discharged: 12, opd: 94 },
    { day: 'Tue', admitted: 22, discharged: 15, opd: 110 },
    { day: 'Wed', admitted: 14, discharged: 19, opd: 88 },
    { day: 'Thu', admitted: 26, discharged: 14, opd: 128 },
    { day: 'Fri', admitted: 20, discharged: 21, opd: 115 },
    { day: 'Sat', admitted: 12, discharged: 9, opd: 65 },
    { day: 'Sun', admitted: 8, discharged: 6, opd: 42 },
  ],
  monthly_revenue_data: [
    { month: 'Apr', revenue: 380000, expenses: 245000 },
    { month: 'May', revenue: 410000, expenses: 260000 },
    { month: 'Jun', revenue: 395000, expenses: 250000 },
    { month: 'Jul', revenue: 430000, expenses: 275000 },
    { month: 'Aug', revenue: 442000, expenses: 280000 },
    { month: 'Sep', revenue: 458200, expenses: 290000 },
  ],
  appointments_by_department: [
    { department: 'Cardiology', count: 34 },
    { department: 'Emergency & Trauma', count: 29 },
    { department: 'General Medicine', count: 24 },
    { department: 'Orthopedics', count: 18 },
    { department: 'Pediatrics', count: 14 },
    { department: 'Neurology', count: 9 },
  ],
  appointment_status_distribution: [
    { name: 'Completed', value: 58 },
    { name: 'Scheduled', value: 36 },
    { name: 'Waiting', value: 18 },
    { name: 'In Consultation', value: 10 },
    { name: 'Cancelled', value: 6 },
  ],
  today_appointments_list: INITIAL_APPOINTMENTS,
  recent_patients: INITIAL_PATIENTS,
  recent_payments: INITIAL_PAYMENTS,
};
